ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: c59bba8fb259db0fec2bbb77ad8ba51ea7341b56  # frozen: v0.15.20
    hooks:
      - id: ruff
        args:
          - "--fix"
        exclude_types:
          - jupyter
      - id: ruff
        name: ruff (notebooks)
        args:
          - "--fix"
        types:
          - jupyter
      - id: ruff-format
        # run via nbqa to handle cell magics
        exclude_types:
          - jupyter
  # run ruff via nbqa, which has better and configurable handling of cell magics
  # than ruff itself
  # but has trouble with isort rules
  - repo: https://github.com/nbQA-dev/nbQA
    rev: f96ec7f3b26a32619435686eb5813235f7e3327e # frozen: 1.9.1
    hooks:
      - id: nbqa-ruff-format
      - id: nbqa-ruff-check
        args:
          - --fix
          # isort rules get confused in the temporary files
          - --ignore=I
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: 39e2973981e6d2f9b6c543b0086a2d2393abdc89  # frozen: v3.9.4
    hooks:
      - id: prettier

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: e3eebf65325ccc992422292cb7a4baee967cf815  # frozen: v1.26.1
    hooks:
      - id: zizmor
        args:
          - --fix=all
      - id: zizmor
        args:
          - --fix=all
          - --config=zizmor-strict.yaml
        files: .github/workflows/release.yml

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: requirements-txt-fixer
  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: 9158d5162f915488785c296b5d08d6d18be10d32 # frozen: v10.3.0
  #   hooks:
  #     - id: eslint
  #       files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
  #       exclude: ipyparallel/nbextension/.*
  #       types: [file]
  #       additional_dependencies:
  #         - "@typescript-eslint/eslint-plugin@8.59.2"
  #         - "@typescript-eslint/parser@2.27.0"
  #         - eslint@^6.0.0
  #         - eslint-config-prettier@6.10.1
  #         - eslint-plugin-prettier@3.1.4
  #         - eslint-plugin-react@7.21.5
  #         - typescript@4.1.3
