services:
  mysql:
    image: mariadb:10.11
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var_lib/mysql

  slurmdbd:
    image: ipp-cluster:slurm
    build: .
    command:
      - slurmdbd
    container_name: slurmdbd
    hostname: slurmdbd
    volumes:
      - etc_munge:/etc/munge
      - var_log_slurm:/var/log/slurm
    depends_on:
      - mysql

  slurmctld:
    image: ipp-cluster:slurm
    build: .
    command:
      - slurmctld
    container_name: slurmctld
    hostname: slurmctld
    volumes:
      - etc_munge:/etc/munge
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ../..:/io
    depends_on:
      - slurmdbd

  compute:
    image: ipp-cluster:slurm
    build: .
    command:
      - slurmd
    deploy:
      replicas: 2

    volumes:
      - etc_munge:/etc/munge
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ../..:/io
    depends_on:
      - "slurmctld"

volumes:
  etc_munge:
  # etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm:
