# Build releases and (on tags) publish to PyPI
name: Release

# always build releases (to make sure wheel-building works)
# but only publish to PyPI on tags
on:
  push:
    branches-ignore:
      - "pre-commit-ci*"
    tags:
      - "*"
  pull_request:

concurrency:
  group: >-
    ${{ github.workflow }}-
    ${{ github.ref_type }}-
    ${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
        with:
          persist-credentials: false
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v6
        with:
          python-version: "3.13"

      - name: install build package
        run: |
          pip install --upgrade pip
          pip install build
          pip freeze

      - name: build release
        run: |
          python -m build --sdist --wheel .
          ls -l dist

      - name: verify wheel
        run: |
          cd dist
          pip install ./*.whl jupyterlab==4.*
          ipcluster --help-all
          ipcontroller --help-all
          ipengine --help-all
          jupyter labextension list 2>&1 | grep ipyparallel
          jupyter server extension list 2>&1 | grep ipyparallel

      # ref: https://github.com/actions/upload-artifact#readme
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: ipyparallel-${{ github.sha }}
          path: "dist/*"
          if-no-files-found: error

  upload-pypi:
    permissions:
      id-token: write
    environment: release
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build-release
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          path: dist
          merge-multiple: true
      - name: Publish wheels to PyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
