# because it's too unbelievably slow to install ssh server on Windows
name: Build image for Windows SSH CI

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ipyparallel-windows-ssh
  TAG: 3.12-2022

jobs:
  build-and-push-image:
    runs-on: windows-2022

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      #       - name: Extract metadata (tags, labels) for Docker
      #         id: meta
      #         uses: docker/metadata-action@v5
      #         with:
      #           labels: |
      #             org.opencontainers.image.title=${{ env.IMAGE_NAME }}
      #
      #           images: ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
      #           tags: |
      #             type=raw,value=${{ env.TAG }}

      - name: Build image
        # can't use build-push-action on Windows
        # https://github.com/docker/build-push-action/issues/18
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} -f ci/ssh/win_base_Dockerfile ci/ssh
      - name: Push image
        run: |
          docker push ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
